### ISSUE TITLE
Output file should start with <!DOCTYPE html>

### ISSUE THREAD

**Issue by fabienleite** [jirihybek/raml2html-modern-theme#1]
Hello and thank you for providing this theme which is great !

## What is wrong

HTML exported file starts with : 

```html
<!doctype html>
```

## What it should be

The tag should probably be in CAPS : 

```html
<!DOCTYPE html>
```
The  HTML standard [describes it as case insensitive](https://html.spec.whatwg.org/multipage/syntax.html#the-doctype) but some implementations seems not to agree with it :

I actually discovered it by having a strange "bug" while uploading my HTML file to github pages. I was getting a 404 on ```https://{myname}.github.io/{my_repo}/``` while ```https://{myname}.github.io/{my_repo}/index.html``` was perfectly fine.

I fixed it for myself by including a ```sed``` command to my CD process but that should probably be fixed in a more reliable way in the code.

**Comment by jirihybek** [comment]
Fixed in v1.0.4.
